### ISSUE TITLE
Build supplies when we are close to supply limit

### ISSUE THREAD

**Issue by alkurbatov** [alkurbatov/suvorov-bot#10]

**Comment by ImpulseCloud** [comment]
The current implementation of this has the following bugs:
* All training/construction orders queued contribute to CalcConsumption (50 marauder orders queued with 1 barracks estimates 100 supply needed and tries to build 12 depots immediately)
* All training/construction orders queued contribute to CalcSupply (10 CommandCenter orders queued estimate we currently have +150 supply available so never builds more supply even if supply-blocked)

I have a solution using a CalcConsumptionRate which estimates supply-training-rate of current production-buildings during the build-time of a new supply depot. E.g.:
            // MarineTrainTime = 18*22.4 (roughly) = 403.2 , TrainRate = 1/403
            // SupplyDepot = 480 framesToTrain, TrainRate = 1/480
            // Marines trained while Depot builds = 480/403 = 1.191

I've tweaked it so it is very smooth and doesn't build Supply when unneeded and doesn't get supply-blocked for more than a few frames ever. I never need to include SupplyDepots in my ConstructionOrders anymore (except for 1st one to prevent a rare Barracks-Before-Supply if I get minerals too quickly).

Should I attach a Pull Request to this closed issue-topic, or should a new one be opened as an 'Improvement' or something?

**Comment by alkurbatov** [comment]
Please, create a new issue.
