### ISSUE TITLE
Reimplement minerals and vespen gathering for Zerg

### ISSUE THREAD

**Issue by alkurbatov** [alkurbatov/suvorov-bot#36]
Currently, playing as a Zerg, leads to impossibility to gather anything, except the starting location.

**Comment by ImpulseCloud** [comment]
This was fixed in Issue #35, "Improve mineral saturation". When drones pop, they call OnCreate/Idle which call DistributeWorker and they get sent to a non-saturated townhall.

I think this can be closed, unless you want to rename it to "Select larva for workers at unsaturated townhalls first".

**Comment by alkurbatov** [comment]
Thank you! Lets close this one.
